BEGIN;

ALTER TABLE eating 
DROP CONSTRAINT child_id,
ADD CONSTRAINT FOREIGN KEY child_id REFERENCES children(id) ON DELETE CASCADE;

ALTER TABLE sleeping 
DROP CONSTRAINT child_id,
ADD CONSTRAINT FOREIGN KEY child_id REFERENCES children(id) ON DELETE CASCADE;

COMMIT;